### ISSUE TITLE
Add support for complex functions

### ISSUE THREAD

**Issue by martinberoiz** [aaronuv/arby#3]
Add support for complex functions in the input.

Do we need complex parameter support as well? I'd guess prolly not?

**Comment by aaronuv** [comment]
The package in the present state doesn't support complex numbers for full surrogate buildings but it does indeed for constructing reduced bases and interpolants. An example, complex waveforms (as functions of time) conforming the training set. Arby can build reduced bases for them.

**Comment by aaronuv** [comment]
I ll close this issue because I think it is solved beforehand. Reduced Basis implementation already supports complex data. For surrogates, probably that makes no clear sense because one could contruct a surrogate for each mode of the complex data.

**Comment by martinberoiz** [comment]
Ok, but then we need a unit test for the complex case. I can write one when I get free time.

**Comment by aaronuv** [comment]
That would be great! Tks
